#!/bin/bash

clear
echo Stopping Picochess ....
sudo service picochess stop
sleep 1
echo Copying files ....
sudo cp -n engine* /opt/picochess/engines/armv7l
sudo cp -n adapt* /opt/picochess/engines/armv7l
sudo cp -n crystalH* /opt/picochess/engines/armv7l
sleep 1
cd /opt/picochess/engines/armv7l/
echo Creating new engines.ini ....
sudo mv -n engines.ini engines.ini.save.adapt
sudo sed wengines.ini engines.ini.save.adapt engines.ini.adapt engines.ini.crystalHoney
sleep 1
echo All done, rebooting ....
sleep 2
sudo reboot
